---
- hosts: 172.31.29.11 
  become: yes
  tasks: 
  - include_tasks: myfiles.yml
  - name: copy a file into node side
    copy:
      src: mystaticfile
      dest: /home/maha/myfolder/mystaticfile
  - name: install apache2 webserver
    apt:
      name: apache2
      state: present

  - name: copy index.j2 file into node side
    template:
       src: myindex.j2
       dest: /var/www/html/index.html

