---
- hosts: all
  become: yes
  gather_facts: yes
  tasks: 
  - name: install webserver on debian node side
    apt:
      name: apache2 
      state: present
    when: ansible_os_family=="Debian"

  - name: start webserver on debian node side 
    service:
      name: apache2
      state: started  
    when: ansible_os_family=="Debian"
   
    