---
- hosts: all
  become: yes
  tasks: 
  - name: install webserver on debian node side
    apt:
      name: apache2 
      state: present

  - name: start webserver on debian node side 
    service:
      name: apache2
      state: started  
   
    